# /home/${USER}/livestreampro/.github/workflows/ci.yml
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: make lint
      - run: make test-backend
      - run: make test-frontend
      - name: Build API gateway image
        run: docker build -t api-gateway:${{ github.sha }} ./backend/cmd/api-gateway
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: api-gateway:${{ github.sha }}
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
